project_id = "rspxejrzthyijxpbywuv"

[functions.generate-product-ideas]
verify_jwt = false

[functions.generate-canvas-suggestions]
verify_jwt = false

[functions.ai-canvas-chat]
verify_jwt = false

[functions.generate-board-diagram]
verify_jwt = false

[functions.generate-architecture]
verify_jwt = false
